import Hero from '@src/components/Home/Hero'
import Personal from '@src/components/Home/Personal'
import Layout from '@src/components/layout'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Hero />
        <Personal />
      </Layout>
    </>
  )
}
