import Banner from '@src/components/Banner'
import Experience from '@src/components/Home/Experience'
// import CarouselIcons from '@src/components/Carousel/CarouselIcons'
import Hero from '@src/components/Home/Hero'
import LastProject from '@src/components/Home/LastProject'
import Personal from '@src/components/Home/Personal'
import Projects from '@src/components/Home/Projects'
import Skills from '@src/components/Home/Skills'
import Layout from '@src/components/layout'
import CertificatePopUp from '@src/components/PopUp/CertificatePopUp'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Banner />
        <Hero />
        <Personal />
        <Skills />
        <Experience />
        <LastProject />
        {/* <Projects /> */}
        <CertificatePopUp />
        {/* <CarouselIcons /> */}
      </Layout>
    </>
  )
}
