export { default as DeviceDesktop } from './DeviceDesktop';
export { default as Discord } from './Discord';
export { default as GitHub } from './GitHub';
export * from './IconsSkills';
export { default as Linkedin } from './Linkedin';
export { default as MoonStars } from './MoonStars';
export * from './Star';
export { default as SunHigh } from './SunHigh';
export { default as Vercel } from './Vercel';
export * from './index';
